### PR TITLE
Move `CurrentTxVersionInfo` function out of the `primitives/transaction.cpp` file

### PR DESCRIPTION
**Pull request by jvff**
# Motivation

The `CurrentTxVersionInfo` function that was added to the `src/primitives/transaction.cpp` led to a couple of issues when compiling [`zcash_script`](https://github.com/ZcashFoundation/zcash_script) on Windows. The first issue was a compilation error, because the function uses [designated initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization) which requires building with C++20 to work on MSVC++. The second issue is that it uses some functions from other compilation units, so it requires adding some more code to be compiled in. Since the function isn't needed for `zcash_script`, it's easier to just compile it out.

# Solution

Move out the function from `src/primitives/transaction.cpp` and into a new `src/primitives/tx_version_info.cpp`. The `Makefile.am` file was also updated so that the Zcash build continues working.

### CODE REVIEW

**Review by teor2345 — COMMENTED** [review]
This looks fine, but if we merge it to our `ZcashFoundation/zcash/master`, we're going to have to force-push or rebase all future `zcash/zcash/master` commits.

What do you think about pushing it as a `ZcashFoundation/zcash/zcash-script-zebra-alpha-18` branch instead?

**Comment by jvff** [comment]
Yeah, merging the PR to this repo doesn't make much sense. I tagged the commit with `v4.5.1-zcash-script-zebra-v1.0.0-alpha.18` :+1:

**Comment by teor2345** [comment]
Marking this PR as draft so we never merge it.

**Comment by teor2345** [comment]
This has been obsoleted by recent zcashd refactors.

**Pull request closed without merging**
